Update release-nuget.yml

diff --git a/.github/workflows/release-nuget.yml b/.github/workflows/release-nuget.yml
--- a/.github/workflows/release-nuget.yml
+++ b/.github/workflows/release-nuget.yml
@@ -15,25 +15,23 @@ jobs:
 
     steps:
     - name: Checkout
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
 
     - name: Setup build environment
-      uses: actions/setup-dotnet@v1
+      uses: actions/setup-dotnet@v3
       with:
         dotnet-version: '6.0.x'
-        include-prerelease: true
 
-    - name: Verify commit exists in origin/main
-      run: |
-        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
-        git branch --remote --contains | grep origin/main
-
-    - name: Set VERSION variable from tag
-      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
-
-    - name: Set version output for job
+    - name: Set VERSION variable from latest tag
       id: set_version
-      run: echo "::set-output name=version::${GITHUB_REF/refs\/tags\/v/}"
+      run: |
+        LATEST_TAG=$(git fetch --tags && git for-each-ref --sort=creatordate --format '%(refname)' refs/tags | tail -n 1)
+        if [[ "${LATEST_TAG}" == "" ]]; then echo "Unable to determine latest tag! Exiting"; exit 1; fi
+        echo "LATEST_TAG: ${LATEST_TAG}"
+        VERSION=${LATEST_TAG/refs\/tags\/v/}
+        echo "VERSION: ${VERSION}"
+        echo "VERSION=${VERSION}" >> $GITHUB_ENV
+        echo "::set-output name=version::${VERSION}"
 
     - name: Set SOLUTION variable to point to solution file
       run: |
@@ -54,7 +52,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
 
     - name: Push to GitHub Packages
       run: dotnet nuget push *.${{ needs.build.outputs.version }}.nupkg --source https://nuget.pkg.github.com/${GITHUB_REPOSITORY%/*}/index.json --api-key ${GITHUB_TOKEN}
@@ -66,7 +64,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
-      uses: actions/checkout@v2
+      uses: actions/checkout@v3
 
     - name: Push to nuget.org
       env:
